name: Build Kivy APK

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK
        uses: ./
        with:
          python-version: '3.11'
          work-dir: '.'
